version: '3.9'
services:
  backend:
    build:
      context: ./server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:80
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend


