version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tree_visualization_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/tree_visualization_db
      ASYNC_DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/tree_visualization_db
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:80
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:


